export const usersDatabase = [
    { id: 1, age: 32, name: "Jebediah" },
    { id: 2, age: 30, name: "Bill" },
    { id: 3, age: 34, name: "Bob" },
    { id: 4, age: 27, name: "Valentina" },
    { id: 5, age: 45, name: "Gene" },
    { id: 6, age: 50, name: "Mortimer" },
    { id: 7, age: 30, name: "Walt" },
    { id: 8, age: 23, name: "Gus" }
];

export const spaceShipsDatabase = [
    { id: 1, pilotId: 1, partIds: [1, 3], meta: { fuel: 20, parts: "40" }, name: "Hello, world!", year: 2017 },
    { id: 2, pilotId: 2, partIds: [1, 3], meta: { fuel: 24, parts: "40" }, name: "Don't mess with me!", year: 1999 },
    { id: 3, pilotId: 2, partIds: [1, 3], meta: { fuel: 22, parts: "40" }, name: "Hello, world!", year: 2015 },
    { id: 4, pilotId: 5, partIds: [1, 3], meta: { fuel: 25, parts: "40" }, name: "Hello, world!", year: 2010 },
    { id: 5, pilotId: 2, partIds: [1, 3], meta: { fuel: 21, parts: "40" }, name: "Hello, world!", year: 2007 },
    { id: 6, pilotId: 20, partIds: [1, 3], meta: { fuel: 10, parts: "40" }, name: "Hello, world!", year: 2001 },
    { id: 7, pilotId: 2, partIds: [1, 3], meta: { fuel: 5, parts: "40" }, name: "Hello, world!", year: 1988 },
    { id: 8, pilotId: 6, partIds: [1, 3], meta: { fuel: 4, parts: "40" }, name: "Hello, world!", year: 1956 },
    { id: 9, pilotId: 2, partIds: [1, 3], meta: { fuel: 0, parts: "40" }, name: "Hello, world!", year: 2002 }
]

export const leftJoin = [
    { "users.id": 1, "users.age": 32, "users.name": "Jebediah", "ships.id": undefined, "ships.pilotId": undefined, "ships.name": undefined, "ships.meta": undefined, "ships.partIds": undefined, "ships.year": undefined },
    { "users.id": 2, "users.age": 50, "users.name": "Bill", "ships.id": 2, "ships.pilotId": 2, "ships.name": "Don't mess with me!", "ships.meta": { "fuel": 24, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1999 },
    { "users.id": 2, "users.age": 50, "users.name": "Bill", "ships.id": 5, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 21, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2007 },
    { "users.id": 2, "users.age": 50, "users.name": "Bill", "ships.id": 7, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 5, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1988 },
    { "users.id": 2, "users.age": 50, "users.name": "Bill", "ships.id": 9, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 0, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2002 },
    { "users.id": 3, "users.age": 34, "users.name": "Bob", "ships.id": undefined, "ships.pilotId": undefined, "ships.name": undefined, "ships.meta": undefined, "ships.partIds": undefined, "ships.year": undefined },
    { "users.id": 4, "users.age": 27, "users.name": "Valentina", "ships.id": undefined, "ships.pilotId": undefined, "ships.name": undefined, "ships.meta": undefined, "ships.partIds": undefined, "ships.year": undefined },
    { "users.id": 5, "users.age": 45, "users.name": "Gene", "ships.id": 4, "ships.pilotId": 5, "ships.name": "Hello, world!", "ships.meta": { "fuel": 25, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2010 },
    { "users.id": 6, "users.age": 50, "users.name": "Mortimer", "ships.id": 8, "ships.pilotId": 6, "ships.name": "Hello, world!", "ships.meta": { "fuel": 4, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1956 },
    { "users.id": 7, "users.age": 30, "users.name": "Walt", "ships.id": undefined, "ships.pilotId": undefined, "ships.name": undefined, "ships.meta": undefined, "ships.partIds": undefined, "ships.year": undefined },
    { "users.id": 8, "users.age": 23, "users.name": "Gus", "ships.id": undefined, "ships.pilotId": undefined, "ships.name": undefined, "ships.meta": undefined, "ships.partIds": undefined, "ships.year": undefined },
    { "users.id": 9, "users.age": 28, "users.name": "Scott", "ships.id": undefined, "ships.pilotId": undefined, "ships.name": undefined, "ships.meta": undefined, "ships.partIds": undefined, "ships.year": undefined }
];

export const rightJoin = [
    { "users.id": 2, "users.age": 50, "users.name": "Bill", "ships.id": 2, "ships.pilotId": 2, "ships.name": "Don't mess with me!", "ships.meta": { "fuel": 24, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1999 },
    { "users.id": 2, "users.age": 50, "users.name": "Bill", "ships.id": 5, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 21, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2007 },
    { "users.id": 2, "users.age": 50, "users.name": "Bill", "ships.id": 7, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 5, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1988 },
    { "users.id": 2, "users.age": 50, "users.name": "Bill", "ships.id": 9, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 0, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2002 },
    { "users.id": 5, "users.age": 45, "users.name": "Gene", "ships.id": 4, "ships.pilotId": 5, "ships.name": "Hello, world!", "ships.meta": { "fuel": 25, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2010 },
    { "users.id": 6, "users.age": 50, "users.name": "Mortimer", "ships.id": 8, "ships.pilotId": 6, "ships.name": "Hello, world!", "ships.meta": { "fuel": 4, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1956 },
    { "users.id": undefined, "users.age": undefined, "users.name": undefined, "ships.id": 6, "ships.pilotId": 20, "ships.name": "Hello, world!", "ships.meta": { "fuel": 10, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2001 },
    { "users.id": undefined, "users.age": undefined, "users.name": undefined, "ships.id": 10, "ships.pilotId": 20, "ships.name": "44", "ships.meta": {}, "ships.partIds": [0, 0], "ships.year": 2008 }
];

export const innerJoin = [
    { "users.id": 2, "users.age": 50, "users.name": "Bill", "ships.id": 2, "ships.pilotId": 2, "ships.name": "Don't mess with me!", "ships.meta": { "fuel": 24, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1999 },
    { "users.id": 2, "users.age": 50, "users.name": "Bill", "ships.id": 5, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 21, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2007 },
    { "users.id": 2, "users.age": 50, "users.name": "Bill", "ships.id": 7, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 5, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1988 },
    { "users.id": 2, "users.age": 50, "users.name": "Bill", "ships.id": 9, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 0, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2002 },
    { "users.id": 5, "users.age": 45, "users.name": "Gene", "ships.id": 4, "ships.pilotId": 5, "ships.name": "Hello, world!", "ships.meta": { "fuel": 25, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2010 },
    { "users.id": 6, "users.age": 50, "users.name": "Mortimer", "ships.id": 8, "ships.pilotId": 6, "ships.name": "Hello, world!", "ships.meta": { "fuel": 4, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1956 }
];

export const outerJoin = [
    { "users.id": 1, "users.age": 32, "users.name": "Jebediah", "ships.id": undefined, "ships.pilotId": undefined, "ships.name": undefined, "ships.meta": undefined, "ships.partIds": undefined, "ships.year": undefined },
    { "users.id": 2, "users.age": 50, "users.name": "Bill", "ships.id": 2, "ships.pilotId": 2, "ships.name": "Don't mess with me!", "ships.meta": { "fuel": 24, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1999 },
    { "users.id": 2, "users.age": 50, "users.name": "Bill", "ships.id": 5, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 21, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2007 },
    { "users.id": 2, "users.age": 50, "users.name": "Bill", "ships.id": 7, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 5, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1988 },
    { "users.id": 2, "users.age": 50, "users.name": "Bill", "ships.id": 9, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 0, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2002 },
    { "users.id": 3, "users.age": 34, "users.name": "Bob", "ships.id": undefined, "ships.pilotId": undefined, "ships.name": undefined, "ships.meta": undefined, "ships.partIds": undefined, "ships.year": undefined },
    { "users.id": 4, "users.age": 27, "users.name": "Valentina", "ships.id": undefined, "ships.pilotId": undefined, "ships.name": undefined, "ships.meta": undefined, "ships.partIds": undefined, "ships.year": undefined },
    { "users.id": 5, "users.age": 45, "users.name": "Gene", "ships.id": 4, "ships.pilotId": 5, "ships.name": "Hello, world!", "ships.meta": { "fuel": 25, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2010 },
    { "users.id": 6, "users.age": 50, "users.name": "Mortimer", "ships.id": 8, "ships.pilotId": 6, "ships.name": "Hello, world!", "ships.meta": { "fuel": 4, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1956 },
    { "users.id": 7, "users.age": 30, "users.name": "Walt", "ships.id": undefined, "ships.pilotId": undefined, "ships.name": undefined, "ships.meta": undefined, "ships.partIds": undefined, "ships.year": undefined },
    { "users.id": 8, "users.age": 23, "users.name": "Gus", "ships.id": undefined, "ships.pilotId": undefined, "ships.name": undefined, "ships.meta": undefined, "ships.partIds": undefined, "ships.year": undefined },
    { "users.id": 9, "users.age": 28, "users.name": "Scott", "ships.id": undefined, "ships.pilotId": undefined, "ships.name": undefined, "ships.meta": undefined, "ships.partIds": undefined, "ships.year": undefined },
    { "users.id": undefined, "users.age": undefined, "users.name": undefined, "ships.id": 6, "ships.pilotId": 20, "ships.name": "Hello, world!", "ships.meta": { "fuel": 10, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2001 },
    { "users.id": undefined, "users.age": undefined, "users.name": undefined, "ships.id": 10, "ships.pilotId": 20, "ships.name": "44", "ships.meta": {}, "ships.partIds": [0, 0], "ships.year": 2008 }
]

export const crossJoin = [
    { "users.id": 1, "users.age": 32, "users.name": "Jebediah", "ships.id": 2, "ships.pilotId": 2, "ships.name": "Don't mess with me!", "ships.meta": { "fuel": 24, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1999 },
    { "users.id": 1, "users.age": 32, "users.name": "Jebediah", "ships.id": 4, "ships.pilotId": 5, "ships.name": "Hello, world!", "ships.meta": { "fuel": 25, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2010 },
    { "users.id": 1, "users.age": 32, "users.name": "Jebediah", "ships.id": 5, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 21, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2007 },
    { "users.id": 1, "users.age": 32, "users.name": "Jebediah", "ships.id": 6, "ships.pilotId": 20, "ships.name": "Hello, world!", "ships.meta": { "fuel": 10, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2001 },
    { "users.id": 1, "users.age": 32, "users.name": "Jebediah", "ships.id": 7, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 5, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1988 },
    { "users.id": 1, "users.age": 32, "users.name": "Jebediah", "ships.id": 8, "ships.pilotId": 6, "ships.name": "Hello, world!", "ships.meta": { "fuel": 4, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1956 },
    { "users.id": 1, "users.age": 32, "users.name": "Jebediah", "ships.id": 9, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 0, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2002 },
    { "users.id": 1, "users.age": 32, "users.name": "Jebediah", "ships.id": 10, "ships.pilotId": 20, "ships.name": "44", "ships.meta": {}, "ships.partIds": [0, 0], "ships.year": 2008 },
    { "users.id": 2, "users.age": 50, "users.name": "Bill", "ships.id": 2, "ships.pilotId": 2, "ships.name": "Don't mess with me!", "ships.meta": { "fuel": 24, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1999 },
    { "users.id": 2, "users.age": 50, "users.name": "Bill", "ships.id": 4, "ships.pilotId": 5, "ships.name": "Hello, world!", "ships.meta": { "fuel": 25, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2010 },
    { "users.id": 2, "users.age": 50, "users.name": "Bill", "ships.id": 5, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 21, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2007 },
    { "users.id": 2, "users.age": 50, "users.name": "Bill", "ships.id": 6, "ships.pilotId": 20, "ships.name": "Hello, world!", "ships.meta": { "fuel": 10, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2001 },
    { "users.id": 2, "users.age": 50, "users.name": "Bill", "ships.id": 7, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 5, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1988 },
    { "users.id": 2, "users.age": 50, "users.name": "Bill", "ships.id": 8, "ships.pilotId": 6, "ships.name": "Hello, world!", "ships.meta": { "fuel": 4, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1956 },
    { "users.id": 2, "users.age": 50, "users.name": "Bill", "ships.id": 9, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 0, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2002 },
    { "users.id": 2, "users.age": 50, "users.name": "Bill", "ships.id": 10, "ships.pilotId": 20, "ships.name": "44", "ships.meta": {}, "ships.partIds": [0, 0], "ships.year": 2008 },
    { "users.id": 3, "users.age": 34, "users.name": "Bob", "ships.id": 2, "ships.pilotId": 2, "ships.name": "Don't mess with me!", "ships.meta": { "fuel": 24, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1999 },
    { "users.id": 3, "users.age": 34, "users.name": "Bob", "ships.id": 4, "ships.pilotId": 5, "ships.name": "Hello, world!", "ships.meta": { "fuel": 25, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2010 },
    { "users.id": 3, "users.age": 34, "users.name": "Bob", "ships.id": 5, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 21, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2007 },
    { "users.id": 3, "users.age": 34, "users.name": "Bob", "ships.id": 6, "ships.pilotId": 20, "ships.name": "Hello, world!", "ships.meta": { "fuel": 10, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2001 },
    { "users.id": 3, "users.age": 34, "users.name": "Bob", "ships.id": 7, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 5, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1988 },
    { "users.id": 3, "users.age": 34, "users.name": "Bob", "ships.id": 8, "ships.pilotId": 6, "ships.name": "Hello, world!", "ships.meta": { "fuel": 4, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1956 },
    { "users.id": 3, "users.age": 34, "users.name": "Bob", "ships.id": 9, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 0, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2002 },
    { "users.id": 3, "users.age": 34, "users.name": "Bob", "ships.id": 10, "ships.pilotId": 20, "ships.name": "44", "ships.meta": {}, "ships.partIds": [0, 0], "ships.year": 2008 },
    { "users.id": 4, "users.age": 27, "users.name": "Valentina", "ships.id": 2, "ships.pilotId": 2, "ships.name": "Don't mess with me!", "ships.meta": { "fuel": 24, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1999 },
    { "users.id": 4, "users.age": 27, "users.name": "Valentina", "ships.id": 4, "ships.pilotId": 5, "ships.name": "Hello, world!", "ships.meta": { "fuel": 25, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2010 },
    { "users.id": 4, "users.age": 27, "users.name": "Valentina", "ships.id": 5, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 21, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2007 },
    { "users.id": 4, "users.age": 27, "users.name": "Valentina", "ships.id": 6, "ships.pilotId": 20, "ships.name": "Hello, world!", "ships.meta": { "fuel": 10, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2001 },
    { "users.id": 4, "users.age": 27, "users.name": "Valentina", "ships.id": 7, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 5, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1988 },
    { "users.id": 4, "users.age": 27, "users.name": "Valentina", "ships.id": 8, "ships.pilotId": 6, "ships.name": "Hello, world!", "ships.meta": { "fuel": 4, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1956 },
    { "users.id": 4, "users.age": 27, "users.name": "Valentina", "ships.id": 9, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 0, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2002 },
    { "users.id": 4, "users.age": 27, "users.name": "Valentina", "ships.id": 10, "ships.pilotId": 20, "ships.name": "44", "ships.meta": {}, "ships.partIds": [0, 0], "ships.year": 2008 },
    { "users.id": 5, "users.age": 45, "users.name": "Gene", "ships.id": 2, "ships.pilotId": 2, "ships.name": "Don't mess with me!", "ships.meta": { "fuel": 24, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1999 },
    { "users.id": 5, "users.age": 45, "users.name": "Gene", "ships.id": 4, "ships.pilotId": 5, "ships.name": "Hello, world!", "ships.meta": { "fuel": 25, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2010 },
    { "users.id": 5, "users.age": 45, "users.name": "Gene", "ships.id": 5, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 21, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2007 },
    { "users.id": 5, "users.age": 45, "users.name": "Gene", "ships.id": 6, "ships.pilotId": 20, "ships.name": "Hello, world!", "ships.meta": { "fuel": 10, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2001 },
    { "users.id": 5, "users.age": 45, "users.name": "Gene", "ships.id": 7, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 5, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1988 },
    { "users.id": 5, "users.age": 45, "users.name": "Gene", "ships.id": 8, "ships.pilotId": 6, "ships.name": "Hello, world!", "ships.meta": { "fuel": 4, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1956 },
    { "users.id": 5, "users.age": 45, "users.name": "Gene", "ships.id": 9, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 0, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2002 },
    { "users.id": 5, "users.age": 45, "users.name": "Gene", "ships.id": 10, "ships.pilotId": 20, "ships.name": "44", "ships.meta": {}, "ships.partIds": [0, 0], "ships.year": 2008 },
    { "users.id": 6, "users.age": 50, "users.name": "Mortimer", "ships.id": 2, "ships.pilotId": 2, "ships.name": "Don't mess with me!", "ships.meta": { "fuel": 24, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1999 },
    { "users.id": 6, "users.age": 50, "users.name": "Mortimer", "ships.id": 4, "ships.pilotId": 5, "ships.name": "Hello, world!", "ships.meta": { "fuel": 25, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2010 },
    { "users.id": 6, "users.age": 50, "users.name": "Mortimer", "ships.id": 5, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 21, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2007 },
    { "users.id": 6, "users.age": 50, "users.name": "Mortimer", "ships.id": 6, "ships.pilotId": 20, "ships.name": "Hello, world!", "ships.meta": { "fuel": 10, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2001 },
    { "users.id": 6, "users.age": 50, "users.name": "Mortimer", "ships.id": 7, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 5, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1988 },
    { "users.id": 6, "users.age": 50, "users.name": "Mortimer", "ships.id": 8, "ships.pilotId": 6, "ships.name": "Hello, world!", "ships.meta": { "fuel": 4, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1956 },
    { "users.id": 6, "users.age": 50, "users.name": "Mortimer", "ships.id": 9, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 0, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2002 },
    { "users.id": 6, "users.age": 50, "users.name": "Mortimer", "ships.id": 10, "ships.pilotId": 20, "ships.name": "44", "ships.meta": {}, "ships.partIds": [0, 0], "ships.year": 2008 },
    { "users.id": 7, "users.age": 30, "users.name": "Walt", "ships.id": 2, "ships.pilotId": 2, "ships.name": "Don't mess with me!", "ships.meta": { "fuel": 24, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1999 },
    { "users.id": 7, "users.age": 30, "users.name": "Walt", "ships.id": 4, "ships.pilotId": 5, "ships.name": "Hello, world!", "ships.meta": { "fuel": 25, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2010 },
    { "users.id": 7, "users.age": 30, "users.name": "Walt", "ships.id": 5, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 21, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2007 },
    { "users.id": 7, "users.age": 30, "users.name": "Walt", "ships.id": 6, "ships.pilotId": 20, "ships.name": "Hello, world!", "ships.meta": { "fuel": 10, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2001 },
    { "users.id": 7, "users.age": 30, "users.name": "Walt", "ships.id": 7, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 5, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1988 },
    { "users.id": 7, "users.age": 30, "users.name": "Walt", "ships.id": 8, "ships.pilotId": 6, "ships.name": "Hello, world!", "ships.meta": { "fuel": 4, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1956 },
    { "users.id": 7, "users.age": 30, "users.name": "Walt", "ships.id": 9, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 0, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2002 },
    { "users.id": 7, "users.age": 30, "users.name": "Walt", "ships.id": 10, "ships.pilotId": 20, "ships.name": "44", "ships.meta": {}, "ships.partIds": [0, 0], "ships.year": 2008 },
    { "users.id": 8, "users.age": 23, "users.name": "Gus", "ships.id": 2, "ships.pilotId": 2, "ships.name": "Don't mess with me!", "ships.meta": { "fuel": 24, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1999 },
    { "users.id": 8, "users.age": 23, "users.name": "Gus", "ships.id": 4, "ships.pilotId": 5, "ships.name": "Hello, world!", "ships.meta": { "fuel": 25, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2010 },
    { "users.id": 8, "users.age": 23, "users.name": "Gus", "ships.id": 5, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 21, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2007 },
    { "users.id": 8, "users.age": 23, "users.name": "Gus", "ships.id": 6, "ships.pilotId": 20, "ships.name": "Hello, world!", "ships.meta": { "fuel": 10, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2001 },
    { "users.id": 8, "users.age": 23, "users.name": "Gus", "ships.id": 7, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 5, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1988 },
    { "users.id": 8, "users.age": 23, "users.name": "Gus", "ships.id": 8, "ships.pilotId": 6, "ships.name": "Hello, world!", "ships.meta": { "fuel": 4, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1956 },
    { "users.id": 8, "users.age": 23, "users.name": "Gus", "ships.id": 9, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 0, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2002 },
    { "users.id": 8, "users.age": 23, "users.name": "Gus", "ships.id": 10, "ships.pilotId": 20, "ships.name": "44", "ships.meta": {}, "ships.partIds": [0, 0], "ships.year": 2008 },
    { "users.id": 9, "users.age": 28, "users.name": "Scott", "ships.id": 2, "ships.pilotId": 2, "ships.name": "Don't mess with me!", "ships.meta": { "fuel": 24, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1999 },
    { "users.id": 9, "users.age": 28, "users.name": "Scott", "ships.id": 4, "ships.pilotId": 5, "ships.name": "Hello, world!", "ships.meta": { "fuel": 25, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2010 },
    { "users.id": 9, "users.age": 28, "users.name": "Scott", "ships.id": 5, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 21, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2007 },
    { "users.id": 9, "users.age": 28, "users.name": "Scott", "ships.id": 6, "ships.pilotId": 20, "ships.name": "Hello, world!", "ships.meta": { "fuel": 10, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2001 },
    { "users.id": 9, "users.age": 28, "users.name": "Scott", "ships.id": 7, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 5, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1988 },
    { "users.id": 9, "users.age": 28, "users.name": "Scott", "ships.id": 8, "ships.pilotId": 6, "ships.name": "Hello, world!", "ships.meta": { "fuel": 4, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 1956 },
    { "users.id": 9, "users.age": 28, "users.name": "Scott", "ships.id": 9, "ships.pilotId": 2, "ships.name": "Hello, world!", "ships.meta": { "fuel": 0, "parts": "40" }, "ships.partIds": [1, 3], "ships.year": 2002 },
    { "users.id": 9, "users.age": 28, "users.name": "Scott", "ships.id": 10, "ships.pilotId": 20, "ships.name": "44", "ships.meta": {}, "ships.partIds": [0, 0], "ships.year": 2008 }];