Object.defineProperty(exports, "__esModule", { value: true });
global._fs = require("fs");
global._path = require("path");
global._levelup = require("levelup");
global._leveldown = require("leveldown");
global._crypto = require("crypto");
var index_1 = require("./index");
exports.NanoSQLInstance = index_1.NanoSQLInstance;
exports.nSQL = index_1.nSQL;
var utilities_1 = require("./utilities");
exports._assign = utilities_1._assign;
